package de.l3s.interweb.core.responses;

import java.util.List;

import io.quarkus.runtime.annotations.RegisterForReflection;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

@RegisterForReflection
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ResponseOutput {
    /**
     * The type of the output.
     * Always present.
     */
    @JsonProperty("type")
    private String type;

    /**
     * The unique ID of the output item.
     */
    @JsonProperty("id")
    private String id;

    /**
     * The status of the item.
     */
    @JsonProperty("status")
    private String status;

    /**
     * The content of the output message or reasoning.
     * Present in: message, reasoning.
     */
    @JsonProperty("content")
    private List<ResponseOutputMessageContent> content;

    /**
     * The role of the output message. Always assistant.
     * Present in: message.
     */
    @JsonProperty("role")
    private String role;

    /**
     * The refusal explanation from the model.
     * Present in: refusal.
     */
    @JsonProperty("refusal")
    private String refusal;

    /**
     * The queries used to search for files.
     * Present in: file_search_call.
     */
    @JsonProperty("queries")
    private List<Object> queries;

    /**
     * The results of the file search tool call.
     * Present in: file_search_call.
     */
    @JsonProperty("results")
    private List<ResponseOutputFileSearchResult> results;

    /**
     * A JSON string of the arguments to pass to the function or tool.
     * Present in: function_call, mcp_call, mcp_approval_request.
     */
    @JsonProperty("arguments")
    private String arguments;

    /**
     * The name of the function or tool.
     * Present in: function_call, mcp_call, mcp_approval_request, custom_tool_call.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The unique ID of the tool call generated by the model.
     * Present in: function_call, computer_call, local_shell_call, shell_call, shell_call_output, apply_patch_call, apply_patch_call_output, custom_tool_call.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * An object describing the specific action taken.
     * Present in: web_search_call, computer_call, local_shell_call, shell_call.
     */
    @JsonProperty("action")
    private Object action;

    /**
     * The pending safety checks for the computer call.
     * Present in: computer_call.
     */
    @JsonProperty("pending_safety_checks")
    private List<Object> pendingSafetyChecks;

    /**
     * Reasoning summary content.
     * Present in: reasoning.
     */
    @JsonProperty("summary")
    private List<Object> summary;

    /**
     * The encrypted content of the reasoning item or compaction item.
     * Present in: reasoning, compaction.
     */
    @JsonProperty("encrypted_content")
    private String encryptedContent;

    /**
     * The ID of the entity that created this tool call.
     * Present in: compaction, shell_call, shell_call_output, apply_patch_call, apply_patch_call_output.
     */
    @JsonProperty("created_by")
    private String createdBy;

    /**
     * The generated image encoded in base64.
     * Present in: image_generation_call.
     */
    @JsonProperty("result")
    private String result;

    /**
     * The code to run.
     * Present in: code_interpreter_call.
     */
    @JsonProperty("code")
    private String code;

    /**
     * The ID of the container used to run the code.
     * Present in: code_interpreter_call.
     */
    @JsonProperty("container_id")
    private String containerId;

    /**
     * The outputs generated by the code interpreter.
     * Present in: code_interpreter_call.
     */
    @JsonProperty("outputs")
    private List<Object> outputs;

    /**
     * The maximum length of the shell command output.
     * Present in: shell_call_output.
     */
    @JsonProperty("max_output_length")
    private Integer maxOutputLength;

    /**
     * The output of the tool call. Can be a List (shell_call_output) or String (apply_patch_call_output, mcp_call).
     * Present in: shell_call_output, apply_patch_call_output, mcp_call.
     */
    @JsonProperty("output")
    private Object output;

    /**
     * The operation applied via apply_patch.
     * Present in: apply_patch_call.
     */
    @JsonProperty("operation")
    private Object operation;

    /**
     * The label of the MCP server.
     * Present in: mcp_call, mcp_list_tools, mcp_approval_request.
     */
    @JsonProperty("server_label")
    private String serverLabel;

    /**
     * Unique identifier for the MCP tool call approval request.
     * Present in: mcp_call.
     */
    @JsonProperty("approval_request_id")
    private String approvalRequestId;

    /**
     * The error from the tool call, if any.
     * Present in: mcp_call, mcp_list_tools.
     */
    @JsonProperty("error")
    private String error;

    /**
     * The tools available on the server.
     * Present in: mcp_list_tools.
     */
    @JsonProperty("tools")
    private List<Object> tools;

    /**
     * The input for the custom tool call generated by the model.
     * Present in: custom_tool_call.
     */
    @JsonProperty("input")
    private String input;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public List<ResponseOutputMessageContent> getContent() {
        return content;
    }

    public void setContent(List<ResponseOutputMessageContent> content) {
        this.content = content;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getRefusal() {
        return refusal;
    }

    public void setRefusal(String refusal) {
        this.refusal = refusal;
    }

    public List<Object> getQueries() {
        return queries;
    }

    public void setQueries(List<Object> queries) {
        this.queries = queries;
    }

    public List<ResponseOutputFileSearchResult> getResults() {
        return results;
    }

    public void setResults(List<ResponseOutputFileSearchResult> results) {
        this.results = results;
    }

    public String getArguments() {
        return arguments;
    }

    public void setArguments(String arguments) {
        this.arguments = arguments;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCallId() {
        return callId;
    }

    public void setCallId(String callId) {
        this.callId = callId;
    }

    public Object getAction() {
        return action;
    }

    public void setAction(Object action) {
        this.action = action;
    }

    public List<Object> getPendingSafetyChecks() {
        return pendingSafetyChecks;
    }

    public void setPendingSafetyChecks(List<Object> pendingSafetyChecks) {
        this.pendingSafetyChecks = pendingSafetyChecks;
    }

    public List<Object> getSummary() {
        return summary;
    }

    public void setSummary(List<Object> summary) {
        this.summary = summary;
    }

    public String getEncryptedContent() {
        return encryptedContent;
    }

    public void setEncryptedContent(String encryptedContent) {
        this.encryptedContent = encryptedContent;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getContainerId() {
        return containerId;
    }

    public void setContainerId(String containerId) {
        this.containerId = containerId;
    }

    public List<Object> getOutputs() {
        return outputs;
    }

    public void setOutputs(List<Object> outputs) {
        this.outputs = outputs;
    }

    public Integer getMaxOutputLength() {
        return maxOutputLength;
    }

    public void setMaxOutputLength(Integer maxOutputLength) {
        this.maxOutputLength = maxOutputLength;
    }

    public Object getOutput() {
        return output;
    }

    public void setOutput(Object output) {
        this.output = output;
    }

    public Object getOperation() {
        return operation;
    }

    public void setOperation(Object operation) {
        this.operation = operation;
    }

    public String getServerLabel() {
        return serverLabel;
    }

    public void setServerLabel(String serverLabel) {
        this.serverLabel = serverLabel;
    }

    public String getApprovalRequestId() {
        return approvalRequestId;
    }

    public void setApprovalRequestId(String approvalRequestId) {
        this.approvalRequestId = approvalRequestId;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public List<Object> getTools() {
        return tools;
    }

    public void setTools(List<Object> tools) {
        this.tools = tools;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }
}

