//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.13 at 07:49:56 PM CEST 
//


package de.l3s.interwebj.connector.vimeo.jaxb;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.l3s.vimeo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NumberOfLikes_QNAME = new QName("", "number_of_likes");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _NumberOfPlays_QNAME = new QName("", "number_of_plays");
    private final static QName _ModifiedDate_QNAME = new QName("", "modified_date");
    private final static QName _UploadDate_QNAME = new QName("", "upload_date");
    private final static QName _NumberOfComments_QNAME = new QName("", "number_of_comments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.l3s.vimeo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Thumbnail }
     * 
     */
    public Thumbnail createThumbnail() {
        return new Thumbnail();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createRsp() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link Videos }
     * 
     */
    public Videos createVideos() {
        return new Videos();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Owner }
     * 
     */
    public Owner createOwner() {
        return new Owner();
    }

    /**
     * Create an instance of {@link Thumbnails }
     * 
     */
    public Thumbnails createThumbnails() {
        return new Thumbnails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_likes")
    public JAXBElement<BigInteger> createNumberOfLikes(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfLikes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_plays")
    public JAXBElement<BigInteger> createNumberOfPlays(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfPlays_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modified_date")
    public JAXBElement<String> createModifiedDate(String value) {
        return new JAXBElement<String>(_ModifiedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "upload_date")
    public JAXBElement<String> createUploadDate(String value) {
        return new JAXBElement<String>(_UploadDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_comments")
    public JAXBElement<BigInteger> createNumberOfComments(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfComments_QNAME, BigInteger.class, null, value);
    }

}
