//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.17 at 10:29:36 AM CEST 
//


package l3s.facebook.objects.user;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}school"/>
 *         &lt;element ref="{}year" minOccurs="0"/>
 *         &lt;element ref="{}concentration" minOccurs="0"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}with" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "school",
    "year",
    "concentration",
    "type",
    "with"
})
@XmlRootElement(name = "education")
public class Education {

    @XmlElement(required = true)
    protected School school;
    protected Year year;
    protected Concentration concentration;
    @XmlElement(required = true)
    protected String type;
    protected With with;

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link School }
     *     
     */
    public School getSchool() {
    	if(school== null)
    		return new School();
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link School }
     *     
     */
    public void setSchool(School value) {
        this.school = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    public Year getYear() {
    	if(year== null)
    		return new Year();
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the concentration property.
     * 
     * @return
     *     possible object is
     *     {@link Concentration }
     *     
     */
    public Concentration getConcentration() {
    	if(concentration== null)
    		return new Concentration();
        return concentration;
    }

    /**
     * Sets the value of the concentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Concentration }
     *     
     */
    public void setConcentration(Concentration value) {
        this.concentration = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
    	if(type== null)
    		return "unknown";
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the with property.
     * 
     * @return
     *     possible object is
     *     {@link With }
     *     
     */
    public With getWith() {
    	if(with== null)
    		return new With();
        return with;
    }

    /**
     * Sets the value of the with property.
     * 
     * @param value
     *     allowed object is
     *     {@link With }
     *     
     */
    public void setWith(With value) {
        this.with = value;
    }

}
