//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 04:40:37 PM CEST 
//


package l3s.facebook.listresponse.permissions;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the l3s.facebook.listresponse.permissions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FriendsInterests_QNAME = new QName("", "friends_interests");
    private final static QName _UserPhotoVideoTags_QNAME = new QName("", "user_photo_video_tags");
    private final static QName _Installed_QNAME = new QName("", "installed");
    private final static QName _UserInterests_QNAME = new QName("", "user_interests");
    private final static QName _FriendsReligionPolitics_QNAME = new QName("", "friends_religion_politics");
    private final static QName _UserLocation_QNAME = new QName("", "user_location");
    private final static QName _FriendsPhotoVideoTags_QNAME = new QName("", "friends_photo_video_tags");
    private final static QName _UserAboutMe_QNAME = new QName("", "user_about_me");
    private final static QName _FriendsEducationHistory_QNAME = new QName("", "friends_education_history");
    private final static QName _FriendsRelationships_QNAME = new QName("", "friends_relationships");
    private final static QName _FriendsLikes_QNAME = new QName("", "friends_likes");
    private final static QName _UserActivities_QNAME = new QName("", "user_activities");
    private final static QName _UserEvents_QNAME = new QName("", "user_events");
    private final static QName _UserPhotos_QNAME = new QName("", "user_photos");
    private final static QName _UserGroups_QNAME = new QName("", "user_groups");
    private final static QName _FriendsWorkHistory_QNAME = new QName("", "friends_work_history");
    private final static QName _UserRelationshipDetails_QNAME = new QName("", "user_relationship_details");
    private final static QName _ReadStream_QNAME = new QName("", "read_stream");
    private final static QName _UserWebsite_QNAME = new QName("", "user_website");
    private final static QName _UserLikes_QNAME = new QName("", "user_likes");
    private final static QName _UserReligionPolitics_QNAME = new QName("", "user_religion_politics");
    private final static QName _UserWorkHistory_QNAME = new QName("", "user_work_history");
    private final static QName _UserHometown_QNAME = new QName("", "user_hometown");
    private final static QName _FriendsPhotos_QNAME = new QName("", "friends_photos");
    private final static QName _FriendsHometown_QNAME = new QName("", "friends_hometown");
    private final static QName _FriendsWebsite_QNAME = new QName("", "friends_website");
    private final static QName _FriendsRelationshipDetails_QNAME = new QName("", "friends_relationship_details");
    private final static QName _UserNotes_QNAME = new QName("", "user_notes");
    private final static QName _UserStatus_QNAME = new QName("", "user_status");
    private final static QName _FriendsStatus_QNAME = new QName("", "friends_status");
    private final static QName _FriendsEvents_QNAME = new QName("", "friends_events");
    private final static QName _FriendsBirthday_QNAME = new QName("", "friends_birthday");
    private final static QName _FriendsGroups_QNAME = new QName("", "friends_groups");
    private final static QName _UserOnlinePresence_QNAME = new QName("", "user_online_presence");
    private final static QName _UserVideos_QNAME = new QName("", "user_videos");
    private final static QName _FriendsVideos_QNAME = new QName("", "friends_videos");
    private final static QName _FriendsAboutMe_QNAME = new QName("", "friends_about_me");
    private final static QName _FriendsActivities_QNAME = new QName("", "friends_activities");
    private final static QName _UserBirthday_QNAME = new QName("", "user_birthday");
    private final static QName _FriendsOnlinePresence_QNAME = new QName("", "friends_online_presence");
    private final static QName _UserEducationHistory_QNAME = new QName("", "user_education_history");
    private final static QName _FriendsLocation_QNAME = new QName("", "friends_location");
    private final static QName _UserRelationships_QNAME = new QName("", "user_relationships");
    private final static QName _FriendsNotes_QNAME = new QName("", "friends_notes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: l3s.facebook.listresponse.permissions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_interests")
    public JAXBElement<BigInteger> createFriendsInterests(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsInterests_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_photo_video_tags")
    public JAXBElement<BigInteger> createUserPhotoVideoTags(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserPhotoVideoTags_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "installed")
    public JAXBElement<BigInteger> createInstalled(BigInteger value) {
        return new JAXBElement<BigInteger>(_Installed_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_interests")
    public JAXBElement<BigInteger> createUserInterests(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserInterests_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_religion_politics")
    public JAXBElement<BigInteger> createFriendsReligionPolitics(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsReligionPolitics_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_location")
    public JAXBElement<BigInteger> createUserLocation(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserLocation_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_photo_video_tags")
    public JAXBElement<BigInteger> createFriendsPhotoVideoTags(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsPhotoVideoTags_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_about_me")
    public JAXBElement<BigInteger> createUserAboutMe(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserAboutMe_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_education_history")
    public JAXBElement<BigInteger> createFriendsEducationHistory(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsEducationHistory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_relationships")
    public JAXBElement<BigInteger> createFriendsRelationships(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsRelationships_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_likes")
    public JAXBElement<BigInteger> createFriendsLikes(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsLikes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_activities")
    public JAXBElement<BigInteger> createUserActivities(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserActivities_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_events")
    public JAXBElement<BigInteger> createUserEvents(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserEvents_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_photos")
    public JAXBElement<BigInteger> createUserPhotos(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserPhotos_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_groups")
    public JAXBElement<BigInteger> createUserGroups(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserGroups_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_work_history")
    public JAXBElement<BigInteger> createFriendsWorkHistory(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsWorkHistory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_relationship_details")
    public JAXBElement<BigInteger> createUserRelationshipDetails(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserRelationshipDetails_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "read_stream")
    public JAXBElement<BigInteger> createReadStream(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReadStream_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_website")
    public JAXBElement<BigInteger> createUserWebsite(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserWebsite_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_likes")
    public JAXBElement<BigInteger> createUserLikes(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserLikes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_religion_politics")
    public JAXBElement<BigInteger> createUserReligionPolitics(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserReligionPolitics_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_work_history")
    public JAXBElement<BigInteger> createUserWorkHistory(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserWorkHistory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_hometown")
    public JAXBElement<BigInteger> createUserHometown(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserHometown_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_photos")
    public JAXBElement<BigInteger> createFriendsPhotos(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsPhotos_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_hometown")
    public JAXBElement<BigInteger> createFriendsHometown(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsHometown_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_website")
    public JAXBElement<BigInteger> createFriendsWebsite(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsWebsite_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_relationship_details")
    public JAXBElement<BigInteger> createFriendsRelationshipDetails(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsRelationshipDetails_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_notes")
    public JAXBElement<BigInteger> createUserNotes(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserNotes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_status")
    public JAXBElement<BigInteger> createUserStatus(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserStatus_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_status")
    public JAXBElement<BigInteger> createFriendsStatus(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsStatus_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_events")
    public JAXBElement<BigInteger> createFriendsEvents(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsEvents_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_birthday")
    public JAXBElement<BigInteger> createFriendsBirthday(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsBirthday_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_groups")
    public JAXBElement<BigInteger> createFriendsGroups(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsGroups_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_online_presence")
    public JAXBElement<BigInteger> createUserOnlinePresence(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserOnlinePresence_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_videos")
    public JAXBElement<BigInteger> createUserVideos(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserVideos_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_videos")
    public JAXBElement<BigInteger> createFriendsVideos(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsVideos_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_about_me")
    public JAXBElement<BigInteger> createFriendsAboutMe(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsAboutMe_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_activities")
    public JAXBElement<BigInteger> createFriendsActivities(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsActivities_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_birthday")
    public JAXBElement<BigInteger> createUserBirthday(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserBirthday_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_online_presence")
    public JAXBElement<BigInteger> createFriendsOnlinePresence(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsOnlinePresence_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_education_history")
    public JAXBElement<BigInteger> createUserEducationHistory(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserEducationHistory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_location")
    public JAXBElement<BigInteger> createFriendsLocation(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsLocation_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_relationships")
    public JAXBElement<BigInteger> createUserRelationships(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserRelationships_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "friends_notes")
    public JAXBElement<BigInteger> createFriendsNotes(BigInteger value) {
        return new JAXBElement<BigInteger>(_FriendsNotes_QNAME, BigInteger.class, null, value);
    }

}
