package de.l3s.interweb.core.chat;

import io.quarkus.runtime.annotations.RegisterForReflection;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import de.l3s.interweb.core.ConnectorResults;

@RegisterForReflection
@JsonIgnoreProperties({"elapsed_time", "created"})
public class Choice extends ConnectorResults {
    /**
     * The index of the choice in the list of choices.
     */
    private int index;

    /**
     * The reason the model stopped generating tokens.
     * This will be stop if the model hit a natural stop point or a provided stop sequence, length if the maximum number of tokens specified
     * in the request was reached, content_filter if content was omitted due to a flag from our content filters, tool_calls if the model called a tool.
     */
    @JsonProperty("finish_reason")
    private String finishReason;

    /**
     * A chat completion message generated by the model.
     */
    private Message message;

    public Choice() {
    }

    public Choice(int index, String finishReason, Message message) {
        this.index = index;
        this.finishReason = finishReason;
        this.message = message;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getFinishReason() {
        return finishReason;
    }

    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }

    public Message getMessage() {
        return message;
    }

    public void setMessage(Message message) {
        this.message = message;
    }
}
