package de.l3s.interweb.core.chat;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.List;

import jakarta.validation.constraints.NotNull;

import io.quarkus.runtime.annotations.RegisterForReflection;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)
public class Message implements Serializable {
    @Serial
    private static final long serialVersionUID = 7110951353515625780L;

    private Long id;
    /**
     * The role of the author of this message.
     */
    @NotNull
    private Role role;
    /**
     * An optional name for the participant.
     * Provides the model information to differentiate between participants of the same role.
     */
    private String name;
    /**
     * The contents of the message.
     */
    private String content;
    /**
     * The refusal message generated by the model.
     */
    private String refusal;
    /**
     * The tool calls generated by the model, such as function calls.
     * We keep it as object, we don't want to care about its internal structure here.
     */
    @JsonProperty("tool_calls")
    private Object toolCalls;
    /**
     * Tool call that this message is responding to.
     */
    @JsonProperty("tool_call_id")
    private String toolCallId;
    /**
     * Annotations for the message, such as URL citations.
     */
    private List<Annotation> annotations;
    /**
     * If the audio output modality is requested, this object contains data about the audio response from the model.
     */
    private Audio audio;
    private Instant created;

    public Message() {
    }

    public Message(final Role role) {
        this.role = role;
    }

    public Message(Role role, String content) {
        this.role = role;
        this.content = content;
        this.created = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(final Role role) {
        this.role = role;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(final String content) {
        this.content = content;
    }

    public String getRefusal() {
        return refusal;
    }

    public void setRefusal(String refusal) {
        this.refusal = refusal;
    }

    public Object getToolCalls() {
        return toolCalls;
    }

    public void setToolCalls(Object toolCalls) {
        this.toolCalls = toolCalls;
    }

    public String getToolCallId() {
        return toolCallId;
    }

    public void setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
    }

    public List<Annotation> getAnnotations() {
        return annotations;
    }

    public void setAnnotations(List<Annotation> annotations) {
        this.annotations = annotations;
    }

    public Audio getAudio() {
        return audio;
    }

    public void setAudio(Audio audio) {
        this.audio = audio;
    }

    public Instant getCreated() {
        return created;
    }

    public void setCreated(final Instant created) {
        this.created = created;
    }

    public static Message system(String content) {
        return new Message(Role.system, content);
    }

    public static Message user(String content) {
        return new Message(Role.user, content);
    }

    public static Message assistant(String content) {
        return new Message(Role.assistant, content);
    }
}
