# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: publish-client

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-client:
    if: github.event_name == 'workflow_dispatch' || (startsWith(github.event.head_commit.message, 'chore(client)') && endsWith(github.event.head_commit.message, 'version release'))
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Publish to GitHub Packages Apache Maven
      run: $MVN -pl interweb-client -am deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
